### ISSUE TITLE
Start from Cli

### ISSUE THREAD

**Issue by shangka** [baba-chene/Baba-is-us#26]
I would love to run it from the command line, could you add the procedure in the readme?

**Comment by Lieunoir** [comment]
Interesting suggestion ! Thank you very much !

**Comment by Lieunoir** [comment]
Is the readme to your liking now ?

**Comment by shangka** [comment]
Looks great!

**Comment by regar42** [comment]
It just doesn't work. SHAME!

**Comment by shangka** [comment]
When running `./gradlew desktop:run`, I get this error:

```
[INFO] L'utilisateur est jeremy, définition de la variable JAVA_HOME
       sur /usr/lib/jvm/java-8-openjdk-amd64/

ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-8-openjdk-amd64/

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

Shame indeed

**Comment by Lieunoir** [comment]
Hope we get this working very soon!

**Comment by regar42** [comment]
Hardcoding usernames is such a shame. You should feel very bad.
I'm considering changing my actual name to be actually able to run your game.

**Comment by DarkKapla** [comment]
It's a mistake of mine, go in "gradlew", and remove lines from 69 to 77.
This will be corrected soon.

**Comment by regar42** [comment]
We are not "randoms".
We are thee venerable ancestors. Pay a little respect.
