### ISSUE TITLE
Server/Client

### ISSUE THREAD

**Issue by Lieunoir** [baba-chene/Baba-is-us#5]
Create sockets to forward/send events.

**Comment by YohannL** [comment]
Why did you chose TCP for your dev?
Have you though about using UDP ?

**Comment by Lieunoir** [comment]
Because I had already used TCP, so it was easier for me to implement it. We did consider using UDP, but the pace of the game doesn't really requires it, so we decided to go for better fiability.

**Comment by DarkKapla** [comment]
TCP is fine
